#include <QObject>
#include <QPointer>
#include <memory>

#define MAXIMUM_RECTANGLE_DISPLAYING_DATA_COUNT 100
#define MAXIMUM_RECTANGLE_DATA_COUNT 100
#define MINIMUM_DISPLAYING_DATA_COUNT 10
#define INITIAL_TOTAL_DATA_RANGE 200
#define INITIAL_DISPLAYING_DATA_RANGE 100
#define LOADING_BATCH_SIZE 500
